### PR TITLE
Fix links in lactofermentation.html

### PR DESCRIPTION
**Pull request by mpiffault**
Fixed links for cumin seeds and turmeric

### CODE REVIEW

**Comment by neauoire** [comment]
You've modified the output file, could also modify the source file?
https://github.com/hundredrabbits/Grimgrains/blob/main/src/inc/lactofermentation.htm

**Comment by mpiffault** [comment]
> Thanks for the fix!
> 
> You've modified the output file, could also modify the source file? https://github.com/hundredrabbits/Grimgrains/blob/main/src/inc/lactofermentation.htm

And that's done !

**Comment by mpiffault** [comment]
And thanks a lot for those resources, that's incredibly useful !

**Comment by neauoire** [comment]
cheers!

**Pull request merged**
