### PR TITLE
Lots of minor fixes

### PR DESCRIPTION
**Pull request by microlith57**
Not yet finished!

Summary:
- Migrated all colors and links to correct format (ingredients)
- Some minor typo corrections (recipes + ingredients)
- Fix many descriptions

@neauoire, I assume the square brackets in `BREF` define both colors and subtypes. I have migrated these into the `Color` part and the description as links, as the formatter was treating them as text.

I need feedback on lines 72, 420 and 423 of `ingredients.ndtl`:
- I have placed the sauerkraut  and mayo in comments as there are no corresponding ingredients. (lines 72 and 423)
- I have used a Wikipedia image of miso to approximate the color of what I think is white miso. (line 420).
  - I have very little idea of what miso is so I am likely to be wrong.

Finally, with all these fancy colors for ingredients now available and parseable, we need to use them somehow in the UI! I thought a square or other shape beside the title would be cool:

fancy square

### CODE REVIEW

**Comment by neauoire** [comment]
Very nice, that's a lot of work! Could you uppercase the `Color` key, so it fits with the standard indental?

**Comment by microlith57** [comment]
Did that! Also fixed spinach having `Desc` instead of `BREF`.

**Comment by neauoire** [comment]
Let me know when you're ready for merge, this will be a massive improvement!

**Comment by microlith57** [comment]
I'm also going to go through the recipes - so only a little longer now!

**Comment by microlith57** [comment]
:) Ready for review, I think! I could only do a few recipes; there are so many!

**Comment by neauoire** [comment]
That is a tremendous upgrade!!!!!

**Comment by neauoire** [comment]
Thank you so much for making grimgrains this much better. I like what you've did to the 404

**Pull request merged**
