### PR TITLE
Add parent-child relationships

### LINKED ISSUE #11: 404: gluten flour
In the [flour](https://grimgrains.com/#flour) page, a similar ingredient is gluten flour. However, clicking the link leads to a 404 page, and `ingredients.ndtl` has no entry for it.

Gluten flour listed (just before end of list):
Screenshot showing gluten flour

404 page:
gluten flour 404

### LINKED ISSUE #13: [Suggestion] Sub-ingredient lists
I suggest that for ingredients such as flour, a list of sub-ingredients should be shown (eg. all purpose, wholewheat, einkorn, etc.) and in these sub-ingredients' pages a link would take you back up.

This could be implemented a bit like in Paradise - a `Parent` ingredient for each ingredient, which can be blank, and then autogenerate everything from there.

### PR DESCRIPTION
**Pull request by microlith57**
**Warning! A whole lot of art is missing (eg. for https://grimgrains.com/#rice) for this so the PR is currently a draft.**

Closes #13
Fixes #11 

Summary:
- Add the `Parent` attribute to ingredients
- Add lists of parents and children for each ingredient
- Exclude parents and children from the 'similar ingredient' list

### CODE REVIEW

**Comment by microlith57** [comment]
Current tasks:
- [ ] Wait for #12 as otherwise conflicts may occur
- [ ] Add all parent-child relationships
- [ ] Resolve situation re. art for generic ingredients (eg. rice) vs specific ones (eg. basmati rice, black rice, etc.)

**Comment by neauoire** [comment]
How do you want to handle parent-child?

**Comment by neauoire** [comment]
A recipe could have a parent as ingredient as well, or is this just for the ingredient's page?

**Comment by microlith57** [comment]
Parent-child relationships are automatically calculated from the `PARENT` tag (exactly like in Paradise, but multiple parents are allowed).
Recipes could also be given parents, but I haven't set this up yet as the `TAGS` seems to work well for them.

**Comment by microlith57** [comment]
Please note the `#service` URL I just added - it allows for easy debugging :)

**Comment by microlith57** [comment]
@neauoire 	@rekkabell Would it be possible for me to help contribute to the art which currently needs doing?

I have already copied some of the icons from one ingredient to another, and modified the black olives to make them green.

**Comment by neauoire** [comment]
Please go ahead :)

**Comment by neauoire** [comment]
Just checked the /service page, that's amazing. 
Do you need a hand with this PR?

**Comment by neauoire** [comment]
wow.
thank you so much for this!

**Pull request merged**
